-- MNR_INV_DETAILS DDL
-- Source: xlsx Sheet 2 "Data" (04-IFIS Supplementary Info - INV Detail by BOL)
-- 14-col combined key since 1.0.5 (BOL added to the key; BOL NULLABLE so the
-- MERGE matches NULL to NULL explicitly).
-- Renamed from TBL_INV_DETAIL_BY_BOL to MNR_INV_DETAILS (RateType INV_DETAIL_BY_BOL unchanged).
IF OBJECT_ID(N'dbo.MNR_INV_DETAILS', N'U') IS NULL
BEGIN
CREATE TABLE dbo.MNR_INV_DETAILS (
    INVOICE_NUM INT NOT NULL,
    TALLY_ID INT NOT NULL,
    TRANSMISSION_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    USER_NAME NVARCHAR(255) NULL,
    INVOICE_DATE DATE NULL,
    MANAGEMENT_UNIT_NAME NVARCHAR(255) NULL,
    MANAGEMENT_UNIT_CODE NVARCHAR(50) NOT NULL,
    CUSTOMER_NAME NVARCHAR(255) NULL,
    CUSTOMER_ID INT NOT NULL,
    ADDRESS_ID INT NOT NULL,
    CUSTOMER_TYPE_CODE NVARCHAR(50) NULL,
    TALLY_TYPE_CODE NVARCHAR(50) NULL,
    LICENCE_NUM NVARCHAR(50) NOT NULL,
    LICENSEE_NAME NVARCHAR(255) NULL,
    APPROVAL_NUM INT NOT NULL,
    APPROVAL_TYPE NVARCHAR(50) NULL,
    PROCESSING_SITE_CODE NVARCHAR(50) NOT NULL,
    PROCESSING_SITE_NAME NVARCHAR(255) NULL,
    SCALING_METHOD_CODE NVARCHAR(50) NOT NULL,
    SPECIES_CODE NVARCHAR(50) NOT NULL,
    SPECIES_NAME NVARCHAR(255) NULL,
    GRADE NVARCHAR(50) NULL,
    SPECIES_GROUP NVARCHAR(100) NULL,
    PRODUCT_SECTOR NVARCHAR(100) NULL,
    TALLY_DESTINATION NVARCHAR(50) NOT NULL,
    TALLY_SPECIES NVARCHAR(50) NULL,
    BOL NVARCHAR(50) NULL,
    MASS_SLIP_NUMBER NVARCHAR(50) NULL,
    TAX_CODE NVARCHAR(50) NULL,
    SCALING_DATE DATE NULL,
    MEASURED_UNITS DECIMAL(18,4) NULL,
    VOLUME DECIMAL(18,4) NULL,
    VOLUME_UNDERSIZE DECIMAL(18,4) NULL,
    MINIMUM_STUMPAGE_RATE DECIMAL(18,6) NULL,
    MINIMUM_STUMPAGE DECIMAL(18,4) NULL,
    RESIDUAL_STUMPAGE_RATE DECIMAL(18,6) NULL,
    RESIDUAL_STUMPAGE DECIMAL(18,4) NULL,
    EXPORT_ADMIN_RATE DECIMAL(18,6) NULL,
    EXPORT_ADMIN DECIMAL(18,4) NULL,
    RENEWAL_RATE DECIMAL(18,6) NULL,
    RENEWAL DECIMAL(18,4) NULL,
    FORESTRY_FUTURES_RATE DECIMAL(18,6) NULL,
    FORESTRY_FUTURES DECIMAL(18,4) NULL,
    FOREST_RESOURCE_INVENTORY_RATE DECIMAL(18,6) NULL,
    FOREST_RESOURCE_INVENTORY DECIMAL(18,4) NULL,
    FOREST_MANAGEMENT_RATE DECIMAL(18,6) NULL,
    FOREST_MANAGEMENT DECIMAL(18,4) NULL,
    LFMC_CONVERSION_RATE DECIMAL(18,6) NULL,
    LFMC_CONVERSION DECIMAL(18,4) NULL,
    TREATY_LANDS_RATE DECIMAL(18,6) NULL,
    TREATY_LANDS DECIMAL(18,4) NULL,
    TOTAL_VALUE DECIMAL(18,4) NULL
);
END
GO

-- Covering index for the 14-col MERGE key (avoids 900-byte UNIQUE limit).
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MNR_INV_DETAILS_14KEY' AND object_id = OBJECT_ID(N'dbo.MNR_INV_DETAILS'))
BEGIN
CREATE NONCLUSTERED INDEX IX_MNR_INV_DETAILS_14KEY
ON dbo.MNR_INV_DETAILS (
    INVOICE_NUM, TALLY_ID, TRANSMISSION_ID, USER_ID, MANAGEMENT_UNIT_CODE,
    CUSTOMER_ID, ADDRESS_ID, LICENCE_NUM, APPROVAL_NUM, PROCESSING_SITE_CODE,
    SCALING_METHOD_CODE, SPECIES_CODE, TALLY_DESTINATION, BOL
);
END
GO

-- Migration for existing databases (1.0.4 -> 1.0.5): replace the old 13-col
-- index. Run in a maintenance window on large tables.
-- IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MNR_INV_DETAILS_13KEY' AND object_id = OBJECT_ID(N'dbo.MNR_INV_DETAILS'))
--     DROP INDEX IX_MNR_INV_DETAILS_13KEY ON dbo.MNR_INV_DETAILS;
-- GO

-- Migration for databases created before the rename (TBL_INV_DETAIL_BY_BOL -> MNR_INV_DETAILS):
-- EXEC sp_rename N'dbo.TBL_INV_DETAIL_BY_BOL', N'MNR_INV_DETAILS';
-- IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_TBL_INV_DETAIL_BY_BOL_14KEY' AND object_id = OBJECT_ID(N'dbo.MNR_INV_DETAILS'))
--     DROP INDEX IX_TBL_INV_DETAIL_BY_BOL_14KEY ON dbo.MNR_INV_DETAILS;
-- IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_TBL_INV_DETAIL_BY_BOL_13KEY' AND object_id = OBJECT_ID(N'dbo.MNR_INV_DETAILS'))
--     DROP INDEX IX_TBL_INV_DETAIL_BY_BOL_13KEY ON dbo.MNR_INV_DETAILS;
-- GO
