USE [ALGONQUIN]
GO

/****** Object:  Table [dbo].[MNR_FACTOR_RATES]    Script Date: 7/21/2026 2:12:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MNR_FACTOR_RATES](
	[TYPE] [varchar](50) NOT NULL,
	[FACTOR_ID] [int] NOT NULL,
	[APPROVAL_NUMBER] [varchar](50) NOT NULL,
	[SCALING_METHOD_CODE] [varchar](50) NOT NULL,
	[TALLY_DESTINATION_CODE] [varchar](50) NOT NULL,
	[TALLY_SPECIES_CODE] [varchar](50) NOT NULL,
	[TALLY_GRADE] [varchar](50) NOT NULL,
	[CONTAINER_CODE] [varchar](50) NOT NULL,
	[CHARGE_TYPE] [varchar](50) NOT NULL,
	[LICENCE_NUMBER] [varchar](50) NOT NULL,
	[ACCOUNT_CODE] [varchar](50) NOT NULL,
	[MANAGEMENT_UNIT] [varchar](50) NOT NULL,
	[REDUCTION_RATE] [float] NOT NULL,
	[EFFECTIVE_DATE] [date] NOT NULL,
	[EXPIRY_DATE] [date] NOT NULL,
	[DESTINATION_CODE] [varchar](50) NOT NULL,
	[PRODUCT_TYPE] [varchar](50) NOT NULL,
	[DESTINATION_TYPE] [varchar](50) NOT NULL,
	[TAX_CODE] [varchar](50) NOT NULL,
	[TAX_RATE] [float] NOT NULL,
	[SPECIES_CODE] [varchar](50) NOT NULL,
	[SPECIES_GROUP] [varchar](50) NOT NULL,
	[GRADE] [varchar](50) NOT NULL,
	[DESTINATION_SHARE] [float] NULL,
	[SPECIES_SHARE] [float] NOT NULL,
	[GRADE_SHARE] [float] NOT NULL,
	[MASS_VOLUME_RATIO] [float] NOT NULL,
	[TREE_LENGTH_TABLE] [float] NOT NULL,
	[CONTAINER_VOLUME] [float] NOT NULL,
	[UNDERSIZE_DEDUCTION] [float] NOT NULL,
	[CULL_DEDUCTION] [float] NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_ID_MNR_FACTOR_RATES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [TYPE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [FACTOR_ID]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [APPROVAL_NUMBER]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [SCALING_METHOD_CODE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [TALLY_DESTINATION_CODE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [TALLY_SPECIES_CODE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [TALLY_GRADE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [CONTAINER_CODE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [CHARGE_TYPE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [LICENCE_NUMBER]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [ACCOUNT_CODE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [MANAGEMENT_UNIT]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [REDUCTION_RATE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('01/01/1900') FOR [EFFECTIVE_DATE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('01/01/1900') FOR [EXPIRY_DATE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [DESTINATION_CODE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [PRODUCT_TYPE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [DESTINATION_TYPE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [TAX_CODE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [TAX_RATE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [SPECIES_CODE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [SPECIES_GROUP]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ('') FOR [GRADE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [SPECIES_SHARE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [GRADE_SHARE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [MASS_VOLUME_RATIO]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [TREE_LENGTH_TABLE]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [CONTAINER_VOLUME]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [UNDERSIZE_DEDUCTION]
GO

ALTER TABLE [dbo].[MNR_FACTOR_RATES] ADD  DEFAULT ((0)) FOR [CULL_DEDUCTION]
GO


