USE [ALGONQUIN]
GO

/****** Object:  Table [dbo].[MNR_RENEWAL_RATES]    Script Date: 7/21/2026 2:14:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MNR_RENEWAL_RATES](
	[TYPE] [varchar](50) NOT NULL,
	[RATE_ID] [int] NOT NULL,
	[MANAGEMENT_UNIT_CODE] [varchar](50) NOT NULL,
	[MANAGEMENT_UNIT_NAME] [varchar](50) NOT NULL,
	[SPECIES_GROUP_CODE] [varchar](50) NOT NULL,
	[SPECIES_GROUP_NAME] [varchar](50) NOT NULL,
	[RATE_TYPE_CODE] [varchar](50) NOT NULL,
	[RATE_TYPE_NAME] [varchar](50) NOT NULL,
	[RATE] [float] NOT NULL,
	[EFFECTIVE_DATE] [date] NOT NULL,
	[EXPIRY_DATE] [date] NOT NULL,
 CONSTRAINT [PK_RATE_ID_MNR_RENEWAL_RATES] PRIMARY KEY CLUSTERED 
(
	[RATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ('') FOR [TYPE]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ((0)) FOR [RATE_ID]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ('') FOR [MANAGEMENT_UNIT_CODE]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ('') FOR [MANAGEMENT_UNIT_NAME]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ('') FOR [SPECIES_GROUP_CODE]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ('') FOR [SPECIES_GROUP_NAME]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ('') FOR [RATE_TYPE_CODE]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ('') FOR [RATE_TYPE_NAME]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ((0)) FOR [RATE]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ('01/01/1900') FOR [EFFECTIVE_DATE]
GO

ALTER TABLE [dbo].[MNR_RENEWAL_RATES] ADD  DEFAULT ('01/01/1900') FOR [EXPIRY_DATE]
GO

-- Ver 2.0
-- Date 7/27/2026
-- Notes: There exists some duplicated [RATE_ID], use ID as the new PK.
-- 1. Drop the existing primary key constraint
ALTER TABLE [dbo].[MNR_RENEWAL_RATES] 
DROP CONSTRAINT [PK_RATE_ID_MNR_RENEWAL_RATES];
GO

-- 2. Add a new auto-incrementing ID column and set it as the Primary Key
ALTER TABLE [dbo].[MNR_RENEWAL_RATES] 
ADD [ID] INT IDENTITY(1,1) NOT NULL,
CONSTRAINT [PK_MNR_RENEWAL_RATES] PRIMARY KEY CLUSTERED ([ID] ASC);
GO