USE [ALGONQUIN]
GO

/****** Object:  Table [dbo].[MNR_STUMPAGE_RATES]    Script Date: 7/21/2026 2:13:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MNR_STUMPAGE_RATES](
	[TYPE] [varchar](50) NOT NULL,
	[RATE_ID] [int] NOT NULL,
	[PRODUCT_TYPE_CODE] [varchar](50) NOT NULL,
	[PRODUCT_TYPE_NAME] [varchar](50) NOT NULL,
	[SPECIES_GROUP_CODE] [varchar](50) NOT NULL,
	[SPECIES_GROUP_NAME] [varchar](50) NOT NULL,
	[RATE_TYPE_CODE] [varchar](50) NOT NULL,
	[RATE_TYPE_NAME] [varchar](50) NOT NULL,
	[RATE] [float] NOT NULL,
	[EFFECTIVE_DATE] [date] NOT NULL,
	[EXPIRY_DATE] [date] NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_RATE_ID_MNR_STUMPAGE_RATES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ('') FOR [TYPE]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ((0)) FOR [RATE_ID]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ('') FOR [PRODUCT_TYPE_CODE]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ('') FOR [PRODUCT_TYPE_NAME]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ('') FOR [SPECIES_GROUP_CODE]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ('') FOR [SPECIES_GROUP_NAME]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ('') FOR [RATE_TYPE_CODE]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ('') FOR [RATE_TYPE_NAME]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ((0)) FOR [RATE]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ('01/01/1900') FOR [EFFECTIVE_DATE]
GO

ALTER TABLE [dbo].[MNR_STUMPAGE_RATES] ADD  DEFAULT ('01/01/1900') FOR [EXPIRY_DATE]
GO


